- name: Install required system packages for Docker
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  tags:
    - docker

- name: Add Docker GPG apt Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true
  tags:
    - docker

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable
    state: present
  tags:
    - docker

- name: Update apt and install docker-ce and docker-compose
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-compose
    state: latest
    update_cache: true
  tags:
    - docker

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
  tags:
    - docker

- name: Start docker deamon
  ansible.builtin.service:
    name: docker
    state: started
  tags:
    - docker

- name: Add docker group
  ansible.builtin.group:
    name: docker
    state: present
  tags:
    - docker

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    group: docker
  tags:
    - docker
