- name: Install git 
  ansible.builtin.apt:
    name: git
  tags:
    - dotfiles

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    force: yes
  tags:
    - dotfiles

- name: Install stow 
  ansible.builtin.apt:
    name: stow
  tags:
    - dotfiles

- name: Unstow dotfiles
  ansible.builtin.shell: cd {{ lookup('env', 'HOME') }}/dotfiles && stow -D "{{ item }}" 
  loop: "{{ dotfiles_stow_folders }}"
  tags:
    - dotfiles

- name: Stow dotfiles
  ansible.builtin.shell: cd {{ lookup('env', 'HOME') }}/dotfiles && stow "{{ item }}" 
  loop: "{{ dotfiles_stow_folders }}"
  tags:
    - dotfiles
