- name: Add neovim ppa 
  ansible.builtin.apt_repository: 
    repo: 'ppa:neovim-ppa/unstable' 
    state: present
  tags:
    - neovim

- name: Install neovim from ppa
  ansible.builtin.apt: 
    name: neovim
    state: present 
  tags:
    - neovim
